# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleExample
  pod 'SurveySparrowSdk', :git => 'https://github.com/surveysparrow/surveysparrow-ios-sdk.git', :tag => '0.4.5'

  target 'SimpleExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleExampleUITests' do
    # Pods for testing
  end

end
